### ISSUE TITLE
Use backport providers for DAG generation

### ISSUE THREAD

**Issue by leahecole** [GoogleCloudPlatform/public-datasets-pipelines#12]
## Description

In preparation for the release of Airflow 2.0 in Composer (Q2 '21), we should be generating DAGs with the [new import paths](org/docs/apache-airflow/stable/upgrading-to-2.html#step-4-import-operators-from-backport-providers). 

From what I can tell, I think it just involves adding the [google backport provider](https://pypi.org/project/apache-airflow-backport-providers-google/) as a dependency and an adjustment of [this json](https://github.com/GoogleCloudPlatform/public-datasets-pipelines/blob/main/scripts/dag_imports.json#L2),  and then regenerating existing DAGs. Using the backport providers now means that when you make the jump to using Airflow 2.0, hypothetically things won't break. 

## Checklist
- [x] I created this issue in accordance with the [Code of Conduct](https://github.com/GoogleCloudPlatform/public-datasets-pipelines/blob/main/CODE_OF_CONDUCT.md).
- [x] This issue is appropriately labeled.

**Comment by adlersantos** [comment]
Closing this, Airflow 2.1 is here! 🎉
