### ISSUE TITLE
Pin dependencies + add bot

### ISSUE THREAD

**Issue by leahecole** [GoogleCloudPlatform/public-datasets-pipelines#28]
## Description

Tell us about what's going on or what your suggestions are.

Pin dependencies to specific versions in the Pipfile and any other relevant requirements files, and add a bot (either whitesource renovate or dependabot) to watch for updates and open PRs. 

Some helpful details or guidelines:

- Include the steps to reproduce an error or issue you're experiencing, along with your environment details
- Share code snippets, logs, diagrams, or other content that can help us further understand your situation
- Avoid sharing sensitive, private information
- Label your issue to indicate which component(s) this request is related to.

## Checklist
- [x] I created this issue in accordance with the [Code of Conduct](https://github.com/GoogleCloudPlatform/public-datasets-pipelines/blob/main/CODE_OF_CONDUCT.md).
- [x] This issue is appropriately labeled.

**Comment by adlersantos** [comment]
Closing this due to having added the dependencies bot (auto version bump) and the license header bots.
